--
-- Dumping data for table `abs_games`
--

INSERT INTO `abs_games` (`gid`, `game_name`, `seo_title`, `game_categories`, `game_description`, `game_tags`, `game_instruction`, `game_controls`, `game_img`, `game_file`, `game_width`, `game_height`, `game_is_featured`, `featured_img`, `game_image_source`, `game_file_source`, `game_total_hits`, `game_today_hits`, `game_last_hit`, `game_rating`, `game_votes`, `game_adddate`, `game_source`, `game_source_id`, `game_is_active`) VALUES
(1, 'Talking Tom Cat', 'talking-tom-cat', '1', 'Talking tom cat can respond when you touch: the chest, stomach, feet, mouth, nose, tail, ears, there will be reactions.\r1. touch him, he grunted.\r2. poking at his head and stomach or feet.\r3. on his tail.\r4. a glass of milk to him. play together with tom, joy and laughter.', '', '', NULL, 'talking-tom-cat.jpg', 'barbie-halloween-dressup.swf', '0', '0', 0, '', 0, NULL, 0, 0, 1391423398, 0, 0, 1390220951, NULL, NULL, 1),
(2, 'Ben 10 - Saving Sparksville', 'ben10-saving-sparksville', '1', 'In this game Ben 10 is fighting a giant robot created by Megawatt. The robot is walking towards the hydro electric dam to power up. You must destroy it before it succeeds. Ben 10 has converted into Heatblast for this purpose. Heatblast is flying on some s', '', '', NULL, 'ben10-saving-sparksville.jpg', 'barbie-halloween-dressup.swf', '0', '0', 0, '', 0, NULL, 0, 0, 1391403301, 0, 0, 1390220952, NULL, NULL, 1),
(3, 'Fruit Ninja', 'fruit-ninja', '1', 'Use your mouse to slice the fruit and avoid to cut the animals.', '', '', NULL, 'fruit-ninja.jpg', 'fruit-ninja.swf', '0', '0', 0, '', 0, NULL, 0, 0, 1391418812, 0, 0, 1390220973, NULL, NULL, 1),
(4, 'Bob Esponja - Burger Bonanza', 'bob-esponja-burger-bonanza', '1', 'Ajude o Bob Esponja a fazer o sanduÃ­che corretamente, com todos os ingredientes na ordem certa, olhando a barra do lado esquerdo para acertar, vendo tanto pelos nomes quanto pelos desenhos dos itens em ordem crescente para acertar.', '', '', NULL, 'bob-esponja-burger-bonanza.jpg', 'barbie-halloween-dressup.swf', '0', '0', 0, '', 0, NULL, 0, 0, 1391394811, 0, 0, 1390220949, NULL, NULL, 1),
(5, 'Cinema Panic', 'cinema-panic', '1', 'Donâ€™t panic! Keep calm...and shovel popcorn.', '', '', NULL, 'cinema-panic.jpg', 'barbie-halloween-dressup.swf', '0', '0', 0, '', 0, NULL, 0, 0, 1391361147, 0, 0, 1390220953, NULL, NULL, 1),
(6, 'Earn to Die Part 2', 'earn-to-die-part-2', '1', 'The zombies are back! Unlock and upgrade vehicles as you drive your way through countless zombie hordes.', '', '', NULL, 'earn-to-die-part-2.jpg', 'barbie-halloween-dressup.swf', '0', '0', 0, '', 0, NULL, 0, 0, 1391422828, 0, 0, 1390220953, NULL, NULL, 1),
(7, 'Kingdom Rush', 'kingdom-rush', '1', 'The kingdom is under attack! Defend your realm against hordes of orcs, trolls, evil wizards and other nasty fiends; armed with a mighty arsenal of warriors and mages of your own!Fight on forests, mountains, and wastelands. Upgrade your towers with special powers, rain fire upon your enemies, summon additional troops, recruit elven warriors and face legendary monsters.', '', '', NULL, 'kingdom-rush.jpg', 'barbie-halloween-dressup.swf', '0', '0', 0, '', 0, NULL, 0, 0, 1391175424, 0, 0, 1390220954, NULL, NULL, 1),
(8, 'Sort My Tiles Alvin and the Chipmu', 'sort-my-tiles-alvin-and-the-chipmu', '1', 'an animated music group created by Ross Bagdasarian, Sr. in 1958. The group consists of three singing animated chipmunks: Alvin, the mischievous troublemaker, who quickly became the star of the group; Simon, the tall, bespectacled intellectual; and Theodo', '', '', NULL, 'sort-my-tiles-alvin-and-the-chipmu.jpg', 'barbie-halloween-dressup.swf', '0', '0', 0, '', 0, NULL, 0, 0, 1391419907, 0, 0, 1390220957, NULL, NULL, 1),
(9, 'Plants vs. Zombies', 'plants-vs-zombies', '1', 'Zombies are invading your home and are after your brains! Thankfully, you have your arsenal of plants to defend you in Plants vs. Zombies! Armed with a garden full of peashooters, melon-paults, and cherry bombs, you`ll need to think fast, and plant faster, to stop the different types of zombies dead in their tracks. Obstacles like a setting sun, creeping fog, and a swimming pool add to the challenge and make sure the fun never dies in this addicting Action/Strategy game!', '', '', NULL, 'plants-vs-zombies.jpg', 'barbie-halloween-dressup.swf', '0', '0', 0, '', 0, NULL, 0, 0, 1391414650, 0, 0, 1390220950, NULL, NULL, 1),
(10, 'Barbie At School Dress Up', 'barbie-at-school-dress-up', '1', 'Barbie mudou de cidade e hoje serÃ¡ o seu primeiro dia de aula em seu novo colÃ©gio. Prepare-a para este importante acontecimento, escolhendo Ã  dedo cada peÃ§a de roupa e acessÃ³rio que ela irÃ¡ vestir', '', '', NULL, 'barbie-at-school-dress-up.jpg', 'barbie-halloween-dressup.swf', '0', '0', 0, '', 0, NULL, 0, 0, 1391419164, 0, 0, 1390220952, NULL, NULL, 1);
