<?php
/*
 ##########################################################
## This script is copyrighted to ArcadeBooster.com and you
## are free to modify the script but duplication, selling
## or transferring of this script is a violation of the
## copyright and purchase agreement.
##
## File Name: meta_langs.php
## Version : 1.5.7.4
## Date : 2015-06-04   18:43:57
##########################################################
 */


$metalanguages = array(
    'abkhazian' => 'ab',
    'afar' => 'aa',
    'afrikaans' => 'af',
    'albanian' => 'sq',
    'amharic' => 'am',
    'arabic' => 'ar',
    'armenian' => 'hy',
    'assamese' => 'as',
    'aymara' => 'ay',
    'azerbaijani' => 'az',
    'bashkir' => 'ba',
    'basque' => 'eu',
    'bengali' => 'bn',
    'bangla' => 'bn',
    'bhutani' => 'dz',
    'bihari' => 'bh',
    'bislama' => 'bi',
    'breton' => 'br',
    'bulgarian' => 'bg',
    'burmese' => 'my',
    'byelorussian' => 'be',
    'cambodian' => 'km',
    'catalan' => 'ca',
    'chinese' => 'zh',
    'corsican' => 'co',
    'croatian' => 'hr',
    'czech' => 'cs',
    'danish' => 'da',
    'dutch' => 'nl',
    'english' => 'en',
    'american' => 'en',
    'esperanto' => 'eo',
    'estonian' => 'et',
    'faeroese' => 'fo',
    'fiji' => 'fj',
    'finnish' => 'fi',
    'french' => 'fr',
    'frisian' => 'fy',
    'gaelic (scots gaelic)' => 'gd',
    'galician' => 'gl',
    'georgian' => 'ka',
    'german' => 'de',
    'greek' => 'el',
    'greenlandic' => 'kl',
    'guarani' => 'gn',
    'gujarati' => 'gu',
    'hausa' => 'ha',
    'hebrew' => 'iw',
    'hindi' => 'hi',
    'hungarian' => 'hu',
    'icelandic' => 'is',
    'indonesian' => 'in',
    'interlingua' => 'ia',
    'interlingue' => 'ie',
    'inupiak' => 'ik',
    'irish' => 'ga',
    'italian' => 'it',
    'japanese' => 'ja',
    'javanese' => 'jw',
    'kannada' => 'kn',
    'kashmiri' => 'ks',
    'kazakh' => 'kk',
    'kinyarwanda' => 'rw',
    'kirghiz' => 'ky',
    'kirundi' => 'rn',
    'korean' => 'ko',
    'kurdish' => 'ku',
    'laothian' => 'lo',
    'latin' => 'la',
    'latvian' => 'lv',
    'lettish' => 'lv',
    'lingala' => 'ln',
    'lithuanian' => 'lt',
    'macedonian' => 'mk',
    'malagasy' => 'mg',
    'malay' => 'ms',
    'malayalam' => 'ml',
    'maltese' => 'mt',
    'maori' => 'mi',
    'marathi' => 'mr',
    'moldavian' => 'mo',
    'mongolian' => 'mn',
    'nauru' => 'na',
    'nepali' => 'ne',
    'norwegian' => 'no',
    'occitan' => 'oc',
    'oriya' => 'or',
    'oromo' => 'om',
    'afan' => 'om',
    'pashto' => 'ps',
    'pushto' => 'ps',
    'persian' => 'fa',
    'polish' => 'pl',
    'portuguese' => 'pt',
    'punjabi' => 'pa',
    'quechua' => 'qu',
    'rhaeto-romance' => 'rm',
    'romanian' => 'ro',
    'russian' => 'ru',
    'samoan' => 'sm',
    'sangro' => 'sg',
    'sanskrit' => 'sa',
    'serbian' => 'sr',
    'serbo-croatian' => 'sh',
    'sesotho' => 'st',
    'setswana' => 'tn',
    'shona' => 'sn',
    'sindhi' => 'sd',
    'singhalese' => 'si',
    'siswati' => 'ss',
    'slovak' => 'sk',
    'slovenian' => 'sl',
    'somali' => 'so',
    'spanish' => 'es',
    'sudanese' => 'su',
    'swahili' => 'sw',
    'swedish' => 'sv',
    'tagalog' => 'tl',
    'tajik' => 'tg',
    'tamil' => 'ta',
    'tatar' => 'tt',
    'tegulu' => 'te',
    'thai' => 'th',
    'tibetan' => 'bo',
    'tigrinya' => 'ti',
    'tonga' => 'to',
    'tsonga' => 'ts',
    'turkish' => 'tr',
    'turkmen' => 'tk',
    'twi' => 'tw',
    'ukrainian' => 'uk',
    'urdu' => 'ur',
    'uzbek' => 'uz',
    'vietnamese' => 'vi',
    'volapuk' => 'vo',
    'welsh' => 'cy',
    'wolof' => 'wo',
    'xhosa' => 'xh',
    'yiddish' => 'ji',
    'yoruba' => 'yo',
    'zulu' => 'zu',
);